frontend:
    layout:
        warning: Pozor!
        danger: Chyba!
        success: Úspech!

config:
    category: Aplikácia
    currency:
        name: 'Globálna mena'
        description: 'Globálna mena používana pri všetkých platbách v ISO-4217 formáte (napr. EUR)'
    site_title:
        name: 'Meno stránky'
        description: 'Základný názov stránky - to čo zobrazí ako titulok okna v prehliadači (napr. Denník N)'
    site_description:
        name: 'Popis stránky'
        description: 'Používa sa v meta dátach stránky (napr. Denník N - Nezávislé Noviny)'
    site_url:
        name: 'Base URL stránky'
        description: 'Základná URL kde beží CRM (napr. https://crm.press)'
    cms_url:
        name: 'CMS URL'
        description: 'URL smerujúca na titulku CMS (napr. https://example.com)'
    contact_email:
        name: 'Kontaktný email'
        description: 'Kontaktný email (napr. info@example.com)'
    default_route:
        name: 'Predvolená routa'
        description: 'Nette routa, ktorá sa má použiť pri requeste na / (napr. Subscriptions:Subscriptions:new)'
    home_route:
        name: 'Predvolená stránka'
        description: 'Nette routa, ktorá sa má použiť pri presmerovaní užívateľa po prihlásení, zmene hesla, a pod (napr. Application:Default:default)'
    not_logged_in_route:
        name: 'Stránka pre neprihlásených'
        description: 'Nette routa, na ktorú má byť používateľ presmerovaný pri návšteve URL, ktorá je dostupná len pre prihlásených používateľov (napr. :Users:Sign:in)'
    layout_name:
        name: 'Layout stránky'
        description: 'Názov layoutu zaregistrovaného jedným z modulov. Pozor, nesprávna nota môže znefunkčniť stránku! (napr. dennikn)'
    og_image:
        name: 'Meta obrázok stránky v predplatnom'
        description: 'URL k obrázku (napr. <code>/layouts/admin/images/logo_with_text.svg</code>)'
    header_block:
        name: 'Kód v hlavičke'
        description: 'Ľubovoľný kód (napr. Google analytics alebo ďalšie), ktorý sa má vložiť do hlavičky šablóny'
    admin_logo:
        name: Admin logo
        description: 'HTML zobrazujúce logo v hlavičke (napr. <code>&lt;a href=&quot;/&quot;&gt;&lt;img height=&quot;50px&quot; style=&quot;float:left; padding: 0.3em; background: #e7e7e7;&quot; src=&quot;/layouts/admin/images/logo.svg&quot; alt=&quot;logo&quot;&gt;&lt;/a&gt;</code>)'
    localized_countries:
        name: Zobraziť krajiny v jazyku používateľa
        description: 'Predvolene sa krajiny zobrazia vo vlastnom jazyku'

integrations:
    config:
        category: Integrácie

user:
    delete_user_data:
        internal_error: "Nastala chyba a nepodarilo sa overiť, či konto môže byť zmazané."

components:
    audit_log_history_widget:
        heading: História zmien
        operation:
            create: vytvorené
            update: upravené
            delete: zmazané
        view_all: Zobraziť celú históriu
        user: používateľom
        system: systémom
